timezones = {
    None : "Eastern Time (US & Canada)",
    "": "Eastern Time (US & Canada)",    
    "Etc/GMT+12": "International Date Line West",
    "Pacific/Midway": "Midway Island",
    "Pacific/Pago_Pago": "American Samoa",
    "Pacific/Honolulu": "Hawaii",
    "America/Juneau": "Alaska",
    "America/Los_Angeles": "Pacific Time (US & Canada)",
    "Etc/GMT+7": "Mountain Time (US & Canada)",
    "Etc/GMT+8": "Pacific Time (US & Canada)",
    "Canada/Pacific": "Pacific Time (US & Canada)",
    "America/Vancouver": "Pacific Time (US & Canada)",
    "PST8PDT": "Pacific Time (US & Canada)",
    "US/Pacific": "Pacific Time (US & Canada)",
    "America/Tijuana": "Tijuana",
    "America/Denver": "Mountain Time (US & Canada)",
    "US/Mountain": "Mountain Time (US & Canada)",
    "Navajo": "Mountain Time (US & Canada)",
    "America/Yellowknife": "Mountain Time (US & Canada)",
    "America/Boise": "Mountain Time (US & Canada)",
    "America/Edmonton": "Mountain Time (US & Canada)",
    "America/Ciudad_Juarez": "Mountain Time (US & Canada)",
    "America/Cambridge_Bay": "Mountain Time (US & Canada)",
    "Canada/Mountain": "Mountain Time (US & Canada)",
    "America/Inuvik": "Mountain Time (US & Canada)",
    "America/Phoenix": "Arizona",
    "America/Chihuahua": "Chihuahua",
    "America/Mazatlan": "Mazatlan",
    "America/Chicago": "Central Time (US & Canada)",
    "America/Rainy_River": "Central Time (US & Canada)",
    "America/Rankin_Inlet": "Central Time (US & Canada)",
    "America/North_Dakota/Beulah": "Central Time (US & Canada)",
    "America/North_Dakota/Center": "Central Time (US & Canada)",
    "America/North_Dakota/New_Salem": "Central Time (US & Canada)",
    "America/Ojinaga": "Central Time (US & Canada)",
    "America/Matamoros": "Central Time (US & Canada)",
    "America/Knox_IN": "Central Time (US & Canada)",
    "America/Indiana/Tell_City": "Central Time (US & Canada)",
    "America/Indiana/Knox": "Central Time (US & Canada)",
    "America/Menominee": "Central Time (US & Canada)",
    "America/Resolute": "Central Time (US & Canada)",
    "US/Indiana-Starke": "Central Time (US & Canada)",
    "US/Central": "Central Time (US & Canada)",
    "Canada/Central": "Central Time (US & Canada)",
    "America/Regina": "Saskatchewan",
    "America/Mexico_City": "Mexico City",
    "America/Monterrey": "Monterrey",
    "America/Guatemala": "Central America",
    "America/New_York": "Eastern Time (US & Canada)",
    "US/Michigan": "Eastern Time (US & Canada)",
    "Canada/Eastern": "Eastern Time (US & Canada)",
    "America/Thunder_Bay": "Eastern Time (US & Canada)",
    "America/Montreal": "Eastern Time (US & Canada)",
    "America/Nassau": "Eastern Time (US & Canada)",
    "America/New_York": "Eastern Time (US & Canada)",
    "America/Nipigon": "Eastern Time (US & Canada)",
    "America/Indiana/Marengo": "Eastern Time (US & Canada)",
    "America/Indiana/Petersburg": "Eastern Time (US & Canada)",
    "America/Indiana/Vevay": "Eastern Time (US & Canada)",
    "America/Indiana/Vincennes": "Eastern Time (US & Canada)",
    "America/Indiana/Winamac": "Eastern Time (US & Canada)",
    "America/Indianapolis": "Eastern Time (US & Canada)",
    "America/Iqaluit": "Eastern Time (US & Canada)",
    "America/Kentucky/Monticello": "Eastern Time (US & Canada)",
    "America/Louisville": "Eastern Time (US & Canada)",
    "America/Pangnirtung": "Eastern Time (US & Canada)",
    "America/Toronto": "Eastern Time (US & Canada)",
    "EST5EDT": "Eastern Time (US & Canada)",
    "US/Eastern": "Eastern Time (US & Canada)",
    "America/Indiana/Indianapolis": "Indiana (East)",
    "America/Bogota": "Bogota",
    "America/Lima": "Lima",
    "America/Halifax": "Atlantic Time (Canada)",
    "America/Caracas": "Caracas",
    "America/La_Paz": "La Paz",
    "America/Santiago": "Santiago",
    "America/St_Johns": "Newfoundland",
    "America/Sao_Paulo": "Brasilia",
    "America/Argentina/Buenos_Aires": "Buenos Aires",
    "America/Montevideo": "Montevideo",
    "America/Guyana": "Georgetown",
    "America/Puerto_Rico": "Puerto Rico",
    "America/Godthab": "Greenland",
    "Atlantic/South_Georgia": "Mid-Atlantic",
    "Atlantic/Azores": "Azores",
    "Atlantic/Cape_Verde": "Cape Verde Is.",
    "Europe/Dublin": "Dublin",
    "Europe/London": "London",
    "Europe/Lisbon": "Lisbon",
    "Africa/Casablanca": "Casablanca",
    "Africa/Monrovia": "Monrovia",
    "Etc/UTC": "UTC",
    "Europe/Belgrade": "Belgrade",
    "Europe/Bratislava": "Bratislava",
    "Europe/Budapest": "Budapest",
    "Europe/Ljubljana": "Ljubljana",
    "Europe/Prague": "Prague",
    "Europe/Sarajevo": "Sarajevo",
    "Europe/Skopje": "Skopje",
    "Europe/Warsaw": "Warsaw",
    "Europe/Zagreb": "Zagreb",
    "Europe/Brussels": "Brussels",
    "Europe/Copenhagen": "Copenhagen",
    "Europe/Madrid": "Madrid",
    "Europe/Paris": "Paris",
    "Europe/Amsterdam": "Amsterdam",
    "Europe/Berlin": "Berlin",
    "Europe/Zurich": "Zurich",
    "Europe/Rome": "Rome",
    "Europe/Stockholm": "Stockholm",
    "Europe/Vienna": "Vienna",
    "Africa/Algiers": "West Central Africa",
    "Europe/Bucharest": "Bucharest",
    "Africa/Cairo": "Cairo",
    "Europe/Helsinki": "Helsinki",
    "Europe/Kiev": "Kyiv",
    "Europe/Riga": "Riga",
    "Europe/Sofia": "Sofia",
    "Europe/Tallinn": "Tallinn",
    "Europe/Vilnius": "Vilnius",
    "Europe/Athens": "Athens",
    "Europe/Istanbul": "Istanbul",
    "Europe/Minsk": "Minsk",
    "Asia/Jerusalem": "Jerusalem",
    "Africa/Harare": "Harare",
    "Africa/Johannesburg": "Pretoria",
    "Europe/Kaliningrad": "Kaliningrad",
    "Europe/Moscow": "Moscow",
    "Europe/Volgograd": "Volgograd",
    "Europe/Samara": "Samara",
    "Asia/Kuwait": "Kuwait",
    "Asia/Riyadh": "Riyadh",
    "Africa/Nairobi": "Nairobi",
    "Asia/Baghdad": "Baghdad",
    "Asia/Tehran": "Tehran",
    "Asia/Muscat": "Muscat",
    "Asia/Baku": "Baku",
    "Asia/Yerevan": "Yerevan",
    "Asia/Kabul": "Kabul",
    "Asia/Yekaterinburg": "Yekaterinburg",
    "Asia/Karachi": "Karachi",
    "Asia/Tashkent": "Tashkent",
    "Asia/Kolkata": "Kolkata",
    "Asia/Kathmandu": "Kathmandu",
    "Asia/Dhaka": "Dhaka",
    "Asia/Colombo": "Sri Jayawardenepura",
    "Asia/Almaty": "Almaty",
    "Asia/Novosibirsk": "Novosibirsk",
    "Asia/Rangoon": "Rangoon",
    "Asia/Bangkok": "Bangkok",
    "Asia/Jakarta": "Jakarta",
    "Asia/Krasnoyarsk": "Krasnoyarsk",
    "Asia/Shanghai": "Beijing",
    "Asia/Chongqing": "Chongqing",
    "Asia/Hong_Kong": "Hong Kong",
    "Asia/Urumqi": "Urumqi",
    "Asia/Kuala_Lumpur": "Kuala Lumpur",
    "Asia/Singapore": "Singapore",
    "Asia/Taipei": "Taipei",
    "Australia/Perth": "Perth",
    "Asia/Irkutsk": "Irkutsk",
    "Asia/Ulaanbaatar": "Ulaanbaatar",
    "Asia/Seoul": "Seoul",
    "Asia/Tokyo": "Tokyo",
    "Asia/Yakutsk": "Yakutsk",
    "Australia/Darwin": "Darwin",
    "Australia/Adelaide": "Adelaide",
    "Australia/Sydney": "Sydney",
    "Australia/Brisbane": "Brisbane",
    "Australia/Hobart": "Hobart",
    "Asia/Vladivostok": "Vladivostok",
    "Pacific/Guam": "Guam",
    "Pacific/Port_Moresby": "Port Moresby",
    "Asia/Magadan": "Magadan",
    "Asia/Kamchatka": "Kamchatka",
    "Asia/Anadyr": "Anadyr",
    "Pacific/Auckland": "Auckland",
    "Pacific/Fiji": "Fiji",
    "Pacific/Tongatapu": "Nuku'alofa"
}

# Note: Some timezones serve multiple locations, hence there might be some cities not represented due to duplicate values.


def convertFromIANATimezone(timeZoneName):
    if(TZ_WIN.__contains__(timeZoneName)):
        return TZ_WIN[timeZoneName]
    else:
        return timeZoneName